#!/usr/bin/env bash
# script that will display information about subdomains

subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

dns_config () {
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dns_config "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dns_config "$domain" "$sub"
fi
