#!/usr/bin/env bash
# Configure domain zone that the subdomain www points to your load-balancer IP (lb-01)

dns_configure () {
    scripts=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_configure "$1" "www"
  dns_configure "$1" "lb-01"
  dns_configure "$1" "web-01"
  dns_configure "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_configure "$1" "$2"
fi
