#!/usr/bin/env bash
# transfer a file from our client to a server that acceps 4 parameters

if [ $# -lt 3 ]; then
     echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
     exit;
fi;
scp -o strictHostkeychecking=no -i "$4" "$1" "$3"@"$2":~/
