#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server

sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install haproxy=2.4.\*
sudo apt update && sudo apt upgrade -y

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 65577-web-01 54.237.65.144:80 check\n\tserver 65577-web-02 54.88.134.53:80 check\n' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
