#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen loadbalancer\n\tbind :80\n\tbalance roundrobin\n\tserver 65577-web-01 54.237.65.144:80 check\n\tserver 65577-web-02 54.88.134.53:80 check\n' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
