#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server

sudo apt -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt install haproxy=2.4.\*
sudo apt-get -y update && sudo apt upgrade

lb="\nfrontend www\n
\tbind *:80\n
\tmode http\n
\tdefault_backend web_servers\n

backend web_servers\n
\tbalance roundrobin\n
\tserver 65577-web-01 54.237.65.144:80 check\n
\tserver 65577-web-02 54.88.134.53:80 check\n
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$lb" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
