#!/usr/bin/env bash
# Displays hours: 0-12, minutes 1-59
hr=0
while [ "$hr" -le 12 ]
do
    echo "Hour: $hr"
    (( h++ ))

    m=1
    while [ "$m" -le 59 ]
    do
	echo "$m"
	(( m++ ))
    done
done
